//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace customer_login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Auth
    {
        [Display(Name = "id")]
        public int ID { get; set; }
        [Display(Name = "name")]
        public string name { get; set; }
        [Display(Name = "email")]
        public string email { get; set; }
        [Display(Name = "password")]
        public string password { get; set; }
        [Display(Name = "role")]
        public string role { get; set; }
    }
}
